
services:
  app:
    image: sonaca/codehub:latest
    ports:
      - "8443:8443"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=codehub
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:9.2
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=codehub
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

volumes:
  mysql_data: